@file:Suppress("SpellCheckingInspection", "unused")

package org.rsmod.api.config.refs

import org.rsmod.api.type.refs.varbit.VarBitReferences

typealias varbits = BaseVarBits

object BaseVarBits : VarBitReferences() {
    val multiway_indicator = find("multiway_indicator", 52603174307098)
    val singleway_plus_indicator = find("singleway_plus_indicator", 52603174350056)

    val stamina_active = find("stamina_active", 81145461762806)
    val stamina_duration = find("stamina_duration", 14272015838872)
    val stamina_duration_extra = find("stamina_duration_extra", 450780931095069)
    val buff_stamina_duration_disabled = find("buff_stamina_duration_disabled", 158374502904462)

    val side_journal_tab = find("side_journal_tab", 58785619230382)

    val rune_pouch_type_1 = find("rune_pouch_type_1", 58682578458515)
    val rune_pouch_quantity_1 = find("rune_pouch_quantity_1", 58682578528674)
    val rune_pouch_type_2 = find("rune_pouch_type_2", 58682578482800)
    val rune_pouch_quantity_2 = find("rune_pouch_quantity_2", 58734098834960)
    val rune_pouch_type_3 = find("rune_pouch_type_3", 58682578505493)
    val rune_pouch_quantity_3 = find("rune_pouch_quantity_3", 58734098887909)
    val rune_pouch_type_4 = find("rune_pouch_type_4", 184134690041806)
    val rune_pouch_quantity_4 = find("rune_pouch_quantity_4", 184134690064987)

    val fountain_of_rune_active = find("fountain_of_rune_active", 19321012454304)
    val in_ba_game = find("barbassault_areaexit_pending", 32870870952627)
    val in_lms_game = find("br_ingame", 70944427565195)
    val blighted_items_allowed = find("blighted_items_allowed", 68007766345792)

    val spellbook = find("spellbook", 22618316409612)
    val buff_charge_spell_disabled = find("buff_charge_spell_disabled", 158374502881764)
    val buff_mark_of_darkness_disabled = find("buff_mark_of_darkness_disabled", 158426023244829)

    val combatlevel_transmit = find("combatlevel_transmit", 56930885834068)
    val combatlevel_decimal_transmit = find("combatlevel_decimal_transmit", 116230836668633)
    val autocast_set = find("autocast_set", 5565072492265)
    val autocast_spell = find("autocast_spell", 5565072497878)
    val autocast_defmode = find("autocast_defmode", 22618316438405)

    val cutscene_status = find("cutscene_status", 52603174306817)
    val fov_clamp = find("fov_clamp", 52603174314724)
    val minimap_state = find("minimap_state", 52603174339590)
    val gravestone_tli_hide = find("gravestone_tli_hide", 87430947458308)

    val option_master_volume_saved = find("option_master_volume_saved", 195623733524963)
    val option_music_saved = find("option_music_saved", 160177715962204)
    val option_sounds_saved = find("option_sounds_saved", 160177715992400)
    val option_areasounds_saved = find("option_areasounds_saved", 160177716018875)
    val option_master_volume_desktop = find("option_master_volume_desktop")
    val option_master_volume_saved_desktop = find("option_master_volume_saved_desktop")
    val option_music_desktop = find("option_music_desktop")
    val option_music_saved_desktop = find("option_music_saved_desktop")
    val option_sounds_desktop = find("option_sounds_desktop")
    val option_sounds_saved_desktop = find("option_sounds_saved_desktop")
    val option_areasounds_desktop = find("option_areasounds_desktop")
    val option_areasounds_saved_desktop = find("option_areasounds_saved_desktop")
    val music_unlock_text_toggle = find("music_unlock_text_toggle", 979759217977)

    val music_area_mode = find("music_area_mode", 979759223975)
    val music_enableloop = find("music_enableloop", 979759177998)

    val option_brightness_remember = find("option_brightness_remember", 147143061250651)
    val settings_category = find("settings_category")
    val settings_selected_setting = find("settings_selected_setting")
    val settings_colour_modal_opened = find("settings_colour_modal_opened")
    val settings_textfield_csv_modal_opened = find("settings_textfield_csv_modal_opened")
    val camera_zoom_mouse_disabled = find("camera_zoom_mouse_disabled", 54354867127892)

    val chatbox_transparency = find("chatbox_transparency", 54354867050503)
    val resizable_stone_arrangement = find("resizable_stone_arrangement", 54354867046720)
    val skull_prevent = find("skull_prevent_enabled", 158426023294720)
    val option_acceptaid = find("option_acceptaid", 22000071917329)
    val has_displayname_transmitter = find("has_displayname_transmitter", 89491762451420)
    val chatmodal_unclamp = find("chatmodal_unclamp", 52603174328291)
    val option_hide_rooftops = find("option_hide_rooftops", 158374502976336)
    val orbs_disabled = find("orbs_disabled")
    val wiki_icon_disabled = find("wiki_icon_disabled")
    val hitsplat_tint_disabled = find("hitsplat_tint_disabled")
    val hitsplat_maxhit_disabled = find("hitsplat_maxhit_disabled")
    val hpbar_hud_boss_disabled = find("hpbar_hud_boss_disabled")
    val hpbar_hud_boss_name_disabled = find("hpbar_hud_boss_name_disabled")
    val hpbar_hud_boss_compact_enabled = find("hpbar_hud_boss_compact_enabled")
    val hpbar_hud_boss_percentage_enabled = find("hpbar_hud_boss_percentage_enabled")
    val hpbar_hud_standard_disabled = find("hpbar_hud_standard_disabled")
    val settings_hd_beta_enabled = find("settings_hd_beta_enabled", 195520692873859)
    val settings_hd_beta_full_hd_or_fake_sd =
        find("settings_hd_beta_full_hd_or_fake_sd", 195520692877642)
    val setting_hd_beta_flag = find("setting_hd_beta_flag", 195520692881425)
    val option_dropwarning_on = find("option_dropwarning_on", 14632658384937)
    val option_dropwarning_value = find("option_dropwarning_value", 14632658390428)
    val hide_pm_alongside_chatbox = find("hide_pm_alongside_chatbox")
    val option_lootnotification_on = find("option_lootnotification_on")
    val option_lootnotification_value = find("option_lootnotification_value")
    val option_lootnotification_untradeables = find("option_lootnotification_untradeables")
    val tli_storebutton_toggle_desktop = find("tli_storebutton_toggle_desktop")
    val boss_killcount_filtered = find("boss_killcount_filtered")
    val purgeignored_status = find("purgeignored_status")
    val alchemy_warning_valuethreshold = find("alchemy_warning_valuethreshold")
    val alchemy_warning_untradeables = find("alchemy_warning_untradeables")
    val option_precise_timing = find("option_precise_timing")
    val option_separate_hours = find("option_separate_hours")
    val option_collection_new_item = find("option_collection_new_item")
    val loginlogout_setting = find("loginlogout_setting")
    val mousecam_disabled = find("mousecam_disabled")
    val followerops_deprioritised = find("followerops_deprioritised")
    val desktop_shiftclickdrop_enabled = find("desktop_shiftclickdrop_enabled")
    val gravestone_supplypiles_disabled = find("gravestone_supplypiles_disabled")
    val ca_task_popup = find("ca_task_popup")
    val ca_task_recompletion_notifications = find("ca_task_recompletion_notifications")
    val ca_failure_notifications_enabled = find("ca_failure_notifications_enabled")
    val ca_refailure_notifications_enabled = find("ca_refailure_notifications_enabled")
    val option_chatbox_mode_autoset = find("option_chatbox_mode_autoset")
    val trade_delay_disabled = find("trade_delay_disabled")
    val runinvert_mode = find("runinvert_mode")
    val questlist_sort_type = find("questlist_sort_type")
    val questlist_hide_lackreqs = find("questlist_hide_lackreqs")
    val questlist_hide_lackrecs = find("questlist_hide_lackrecs")
    val questlist_hide_not_started = find("questlist_hide_not_started")
    val questlist_hide_in_progress = find("questlist_hide_in_progress")
    val questlist_hide_completed = find("questlist_hide_completed")
    val questlist_hide_miniquests = find("questlist_hide_miniquests")
    val questlist_hide_quests = find("questlist_hide_quests")
    val questlist_larger_text = find("questlist_larger_text")
    val questlist_disable_text_shadow = find("questlist_disable_text_shadow")
    val questlist_disable_headers = find("questlist_disable_headers")
    val wilderness_lever_blockwarning_standard = find("wilderness_lever_blockwarning_standard")
    val wilderness_lever_blockwarning_highrisk = find("wilderness_lever_blockwarning_highrisk")
    val wildy_hub_warning = find("wildy_hub_warning")
    val wildy_hub_warning_highrisk = find("wildy_hub_warning_highrisk")
    val wildy_canoe_warning = find("wildy_canoe_warning")
    val wildy_canoe_warning_highrisk = find("wildy_canoe_warning_highrisk")
    val option_content_recommender_hide = find("option_content_recommender_hide")
    val option_item_retrieval_warning_disabled = find("option_item_retrieval_warning_disabled")
    val option_ge_price_buy_warning_disabled = find("option_ge_price_buy_warning_disabled")
    val option_ge_price_sell_warning_disabled = find("option_ge_price_sell_warning_disabled")
    val take_ammo_toggle = find("take_ammo_toggle")
    val tradeoption_disabled = find("tradeoption_disabled")
    val purgeignored_permbanned_disabled = find("purgeignored_permbanned_disabled")
    val purgeignored_permmuted_enabled = find("purgeignored_permmuted_enabled")
    val option_level_up_message_disabled = find("option_level_up_message_disabled")
    val worldswitcher_disable_confirmation = find("worldswitcher_disable_confirmation")
    val gravestone_disable_warning = find("gravestone_disable_warning")
    val option_skill_guide = find("option_skill_guide")
    val compass_reorientation_setheight = find("compass_reorientation_setheight")
    val crm_surprisepopup_blocked = find("crm_surprisepopup_blocked")
    val settings_gravestone_autoequip = find("settings_gravestone_autoequip")
    val rightclick_report_abuse_disabled = find("rightclick_report_abuse_disabled")
    val option_trail_reminder_beginner = find("option_trail_reminder_beginner")
    val settings_hit_sounds = find("settings_hit_sounds")
    val settings_transmit_pronouns = find("settings_transmit_pronouns")
    val runenergy_autoenable = find("runenergy_autoenable")
    val bank_depositbox_oplocu_askquantity = find("bank_depositbox_oplocu_askquantity")
    val clan_disable_lastseen = find("clan_disable_lastseen")
    val settings_didyouknow_disabled = find("settings_didyouknow_disabled")
    val option_camera_effect_snow_disabled = find("option_camera_effect_snow_disabled")
    val settings_world_map_hotkey_disabled = find("settings_world_map_hotkey_disabled")
    val settings_interface_resizing = find("settings_interface_resizing")
    val settings_colourful_fade_disabled = find("settings_colourful_fade_disabled")
    val settings_new_menu_interface = find("settings_new_menu_interface")
    val settings_new_menu_transparent_interface_disabled =
        find("settings_new_menu_transparent_interface_disabled")
    val settings_runepouch_loadout_names_disabled =
        find("settings_runepouch_loadout_names_disabled")
    val settings_quetzalwhistle_default_tp = find("settings_quetzalwhistle_default_tp")
    val music_current_playlist = find("music_current_playlist")
    val use_previous_music_mode_on_login = find("use_previous_music_mode_on_login")
    val settings_music_default_track_on_area_entry =
        find("settings_music_default_track_on_area_entry")
    val dont_update_music_on_playlist_change = find("dont_update_music_on_playlist_change")
    val use_shuffle_mode_on_manual_music_selection =
        find("use_shuffle_mode_on_manual_music_selection")
    val option_level_up_chatbox_list = find("option_level_up_chatbox_list")
    val option_level_up_guide_list_disabled = find("option_level_up_guide_list_disabled")
    val option_loottracker_ignorelist_has_text = find("option_loottracker_ignorelist_has_text")
    val combat_weapon_category = find("combat_weapon_category", 43432547647987)
    val keybinding_esc_to_close = find("keybinding_esc_to_close", 63061810400789)

    val demonslayer_main = find("demonslayer_main", 11438395171949)
    val lost_tribe_progress = find("lost_tribe_quest", 23957846140009)
    val kr_knightwaves_state = find("kr_knightwaves_state", 54097265147926)

    val emote_glassbox = find("emote_glassbox", 16126749241145)
    val emote_climbrope = find("emote_climbrope", 16126749244928)
    val emote_lean = find("emote_lean", 16126749248711)
    val emote_glasswall = find("emote_glasswall", 16126749237362)
    val sos_emote_idea = find("sos_emote_idea", 41320212308399)
    val sos_emote_stamp = find("sos_emote_stamp", 41320212312182)
    val sos_emote_flap = find("sos_emote_flap", 41320212300833)
    val sos_emote_doh = find("sos_emote_doh", 41320212304616)
    val emote_zombie_walk = find("emote_zombie_walk", 16126749260608)
    val emote_zombie_dance = find("emote_zombie_dance", 16126749256825)
    val emote_terrified = find("emote_terrified", 16126749252494)
    val emote_bunny_hop = find("emote_bunny_hop", 16126749264524)
    val emote_drilldemon = find("emote_drilldemon", 16126749282329)
    val emote_party = find("emote_party", 16126749321967)
    val emote_zombie_hand = find("emote_zombie_hand", 16126749271033)
    val emote_ash = find("emote_ash", 16126749289963)
    val emote_musiccape = find("emote_musiccape", 16126749278488)
    val emote_uri_transform = find("emote_uri_transform", 16126749294047)
    val emote_hotline_bling = find("emote_hotline_bling", 16126749298322)
    val emote_gangnam = find("emote_gangnam", 16126749302105)
    val emote_premier_club_2018 = find("emote_premier_club_2018", 16126749306330)
    val emote_flex = find("emote_flex", 16126749323697)
    val emote_explore = find("emote_explore", 16126749314186)
    val poh_leaguehall_outfitstand_relichunter_type =
        find("poh_leaguehall_outfitstand_relichunter_type", 148688672513070)
    val emote_trick = find("emote_trick", 16126749334521)

    val enabled_prayers = find("prayer_allactive", 4276218542473)
    val quickprayer_active = find("quickprayer_active", 19321012450480)

    val thick_skin = find("prayer_thickskin", 4276218540768)
    val burst_of_strength = find("prayer_burstofstrength", 4276218544551)
    val clarity_of_thought = find("prayer_clarityofthought", 4276218548334)
    val rock_skin = find("prayer_rockskin", 4276218552117)
    val superhuman_strength = find("prayer_superhumanstrength", 4276218555900)
    val improved_reflexes = find("prayer_improvedreflexes", 4276218559683)
    val rapid_restore = find("prayer_rapidrestore", 4276218563466)
    val rapid_heal = find("prayer_rapidheal", 4276218567249)
    val protect_item = find("prayer_protectitem", 4276218571032)
    val steel_skin = find("prayer_steelskin", 4276218574815)
    val ultimate_strength = find("prayer_ultimatestrength", 4276218578598)
    val incredible_reflexes = find("prayer_incrediblereflexes", 4276218582381)
    val protect_from_magic = find("prayer_protectfrommagic", 4276218586164)
    val protect_from_missiles = find("prayer_protectfrommissiles", 4276218589947)
    val protect_from_melee = find("prayer_protectfrommelee", 4276218593730)
    val retribution = find("prayer_retribution", 4276218597513)
    val redemption = find("prayer_redemption", 4276218601296)
    val smite = find("prayer_smite", 4276218605079)
    val preserve = find("prayer_preserve", 4276218648026)
    val sharp_eye = find("prayer_sharpeye", 4276218608862)
    val mystic_will = find("prayer_mysticwill", 4276218612645)
    val hawk_eye = find("prayer_hawkeye", 4276218616428)
    val mystic_lore = find("prayer_mysticlore", 4276218620211)
    val eagle_eye = find("prayer_eagleeye", 4276218623994)
    val mystic_might = find("prayer_mysticmight", 4276218627777)
    val chivalry = find("prayer_chivalry", 4276218635342)
    val piety = find("prayer_piety", 4276218639125)
    val rigour = find("prayer_rigour", 4276218632896)
    val augury = find("prayer_augury", 4276218644243)
    val preserve_unlocked = find("prayer_preserve_unlocked", 73623487039670)
    val rigour_unlocked = find("prayer_rigour_unlocked", 73623487032104)
    val augury_unlocked = find("prayer_augury_unlocked", 73623487035887)
    val prayer_deadeye_unlocked = find("prayer_deadeye_unlocked", 239828214727554)
    val prayer_mystic_vigour_unlocked = find("prayer_mystic_vigour_unlocked", 239828214731337)

    val toa_client_raid_level = find("toa_client_raid_level", 185062056826088)

    val settings_hitsplat_threshold = find("settings_hitsplat_threshold", 183001241817303)

    val date_ms_past_minute = find("date_milliseconds_past_minute", 158529050136898)
    val date_secs_past_minute = find("date_seconds_past_minute", 158529050174475)

    /* Server-side-only types */
    val music_last_id = find("music_last_id")
    val music_curr_area = find("music_curr_area")
    val music_curr_id = find("music_curr_id")
    val music_curr_clocks = find("music_curr_clocks")
    val music_curr_duration = find("music_curr_duration")
    val gameframe_toplevel = find("gameframe_toplevel")
    val improved_stamina_passive = find("improved_stamina_passive")
    val prayer_drain_counter = find("prayer_drain_counter")
    val prayer_drain_resistance = find("prayer_drain_resistance")
    val new_player_account = find("new_player_account")
    val saved_autocast_spell_staff = find("saved_autocast_spell_staff")
    val saved_defensive_casting_staff = find("saved_defensive_casting_staff")
    val saved_autocast_spell_bladed_staff = find("saved_autocast_spell_bladed_staff")
    val saved_defensive_casting_bladed_staff = find("saved_defensive_casting_bladed_staff")
    val accept_aid_restore = find("accept_aid_restore")
    val bank_capacity = find("bank_capacity")
    val coal_bag_storage_count = find("coal_bag_storage_count")
    val small_pouch_storage_type = find("small_pouch_storage_type")
    val small_pouch_storage_count = find("small_pouch_storage_count")
    val medium_pouch_storage_type = find("medium_pouch_storage_type")
    val medium_pouch_storage_count = find("medium_pouch_storage_count")
    val large_pouch_storage_type = find("large_pouch_storage_type")
    val large_pouch_storage_count = find("large_pouch_storage_count")
    val giant_pouch_storage_type = find("giant_pouch_storage_type")
    val giant_pouch_storage_count = find("giant_pouch_storage_count")
    val colossal_pouch_storage_type = find("colossal_pouch_storage_type")
    val colossal_pouch_storage_count = find("colossal_pouch_storage_count")
}
